"""
Lab Step 1: Vector Embeddings and Cosine Similarity Search
"""

import numpy as np
from app.dependencies import SessionLocal, init_db
from app.models import DocumentChunk
from loguru import logger


def print_separator(title: str) -> None:
    logger.info(f"{'=' * 20} {title} {'=' * 20}")


def main():
    init_db()

    print_separator("SEEDING VECTOR EMBEDDINGS")
    with SessionLocal() as session:
        # In the real world, these float arrays are generated by an LLM (e.g., OpenAI, HuggingFace).
        # We are using 3D coordinates so human brains can visualize the geometry.
        docs = [
            DocumentChunk(content="A cat sleeping on the couch", embedding=[0.9, 0.1, 0.0]),
            DocumentChunk(content="A dog playing in the park", embedding=[0.8, 0.2, 0.1]),
            DocumentChunk(content="Python async programming tutorial", embedding=[0.0, 0.9, 0.2]),
            DocumentChunk(content="SQLAlchemy connection pooling", embedding=[0.1, 0.8, 0.4]),
            DocumentChunk(content="Baking a chocolate cake", embedding=[0.1, 0.0, 0.9]),
        ]
        session.add_all(docs)
        session.commit()
        logger.success("Seeded 5 document chunks with 3D vector embeddings.")

    print_separator("PERFORMING K-NEAREST NEIGHBOR (KNN) SEARCH")
    with SessionLocal() as session:
        # User searches for: "How to tune database connections"
        # The app sends this to an LLM, which returns this embedding:
        search_embedding = np.array([0.05, 0.85, 0.35])
        logger.info(f"User Query Embedding: {search_embedding}")

        logger.warning("Executing Cosine Similarity Search (<=>)...")
        # In SQLAlchemy + pgvector, we use the cosine_distance method
        # ORDER BY the distance ascending, LIMIT 2 (to get the Top 2 closest matches)
        results = (
            session.query(DocumentChunk, DocumentChunk.embedding.cosine_distance(search_embedding).label("distance"))
            .order_by(DocumentChunk.embedding.cosine_distance(search_embedding))
            .limit(2)
            .all()
        )

        for doc, distance in results:
            logger.success(f"Distance: {distance:.4f} | Match: {doc.content}")

        logger.info(
            "Notice how the database perfectly identified the Python and SQLAlchemy documents as semantically closest to the query, and ignored the pets and baking documents!"
        )


if __name__ == "__main__":
    main()
